// Data global para toda la aplicación
window.MATERIALS_DATA = {
  marmoles: [
    { id: 'botticcino',     name: 'Botticcino',     img: 'images/marmoles/Botticcino.webp',       mesa: 'images/mesas/botticcino.webp',       tex: 'crema' },
    { id: 'carrara',        name: 'Carrara',         img: 'images/marmoles/Carrara.webp',           mesa: 'images/mesas/carrara.webp',          tex: 'blanco-gris' },
    { id: 'negro-marquina', name: 'Negro Marquina',  img: 'images/marmoles/Negro-marquina.webp',    mesa: 'images/mesas/negro-marquina.webp',   tex: 'negro' },
    { id: 'new-beige',      name: 'New Beige',       img: 'images/marmoles/New-Beige.webp',         mesa: 'images/mesas/new-beige.webp',        tex: 'crema' },
    { id: 'crema-marfil',   name: 'Crema Marfil',    img: 'images/marmoles/Crema-marfil.webp',      mesa: 'images/mesas/crema-marfil.webp',     tex: 'crema' },
    { id: 'carrara-blanco', name: 'Carrara Blanco',  img: 'images/marmoles/Carrara-Blanco.webp',    mesa: 'images/mesas/carrara-blanco.webp',   tex: 'blanco' },
  ],
  granitos: [
    { id: 'gris-mara',        name: 'Gris Mara',        img: 'images/granitos/gris-mara.webp',         mesa: 'images/mesas/gris-mara.webp',        tex: 'gris-granito' },
    { id: 'rosa-salto',       name: 'Rosa del Salto',   img: 'images/granitos/rosa-del-salto.webp',    mesa: 'images/mesas/rosa-del-salto.webp',   tex: 'beige-granito' },
    { id: 'rosa-mara',        name: 'Rosa Mara',         img: 'images/granitos/rosa-mara.webp',          mesa: 'images/mesas/rosa-mara.webp',        tex: 'beige-rosa' },
    { id: 'sierra-chica',     name: 'Sierra Chica',      img: 'images/granitos/sierra-chica.webp',       mesa: 'images/mesas/sierra-chica.webp',     tex: 'rojizo-granito' },
    { id: 'blanco-fortaleza', name: 'Blanco Fortaleza',  img: 'images/granitos/blanco-fortaleza.webp',   mesa: 'images/mesas/blanco-fortaleza.webp', tex: 'gris-fino' },
    { id: 'gris-perla',       name: 'Gris Perla',        img: 'images/granitos/gris-perla.webp',        mesa: 'images/mesas/gris-perla.webp',       tex: 'gris-claro' },
    { id: 'negro-brasil',     name: 'Negro Brasil',      img: 'images/granitos/gris-mara.webp',          mesa: 'images/mesas/negro-brasil.webp',     tex: 'negro' },
    { id: 'negro-cosmic',     name: 'Negro Cosmic',      img: 'images/granitos/gris-perla.webp',        mesa: 'images/mesas/negro-cosmic.webp',     tex: 'negro-cosmic' },
    { id: 'crema-julia',      name: 'Crema Julia',       img: 'images/granitos/rosa-del-salto.webp',     mesa: 'images/mesas/crema-julia.webp',      tex: 'crema' },
    { id: 'negro-boreal',     name: 'Negro Boreal',      img: 'images/granitos/negro-boreal.webp',       mesa: 'images/mesas/negro-boreal.webp',     tex: 'negro-boreal' },
  ],
  purastone: [
    { id: 'blanco-cana',    name: 'Blanco Caña',    img: 'images/purastone/blanco-cana.webp',     mesa: 'images/mesas/blanco-cana.webp',      tex: 'blanco' },
    { id: 'blanco-glitter', name: 'Blanco Glitter', img: 'images/purastone/blanco-glitter.webp',  mesa: 'images/mesas/blanco-glitter.webp',   tex: 'blanco' },
    { id: 'blanco-paloma',  name: 'Blanco Paloma',  img: 'images/purastone/blanco-paloma.webp',   mesa: 'images/mesas/blanco-paloma.webp',    tex: 'blanco' },
    { id: 'gris-topo',      name: 'Gris Topo',      img: 'images/purastone/gris-topo.webp',       mesa: 'images/mesas/gris-topo.webp',        tex: 'azul-suave' },
    { id: 'negro-glitter',  name: 'Negro Glitter',  img: 'images/purastone/negro-glitter.webp',   mesa: 'images/mesas/negro-glitter.webp',    tex: 'negro-cosmic' },
    { id: 'blanco-nube',    name: 'Blanco Nube',    img: 'images/purastone/blanco-nube.webp',     mesa: 'images/mesas/blanco-nube.webp',      tex: 'blanco-gris' },
    { id: 'taj-mahal',      name: 'Taj Mahal',      img: 'images/purastone/taj-mahal.webp',      mesa: 'images/mesas/taj-mahal.webp',        tex: 'blanco-gris' },
    { id: 'tundra-dark',    name: 'Tundra Dark',    img: 'images/purastone/tundra-dark.webp',    mesa: 'images/mesas/tundra-dark.webp',      tex: 'negro-boreal' },
    { id: 'gris-fosil',     name: 'Gris Fósil',     img: 'images/purastone/blanco-paloma.webp',   mesa: 'images/mesas/gris-fosil.webp',       tex: 'beige-azul' },
    { id: 'gris-zen',       name: 'Gris Zen',       img: 'images/purastone/gris-topo.webp',       mesa: 'images/mesas/gris-zen.webp',         tex: 'gris-claro' },
  ],
  cocinas: [
    { id: 'cocina-l', name: 'Cocina en L', img: 'images/cocinas/cocina-L.webp' },
    { id: 'cocina-integral', name: 'Cocina Integral', img: 'images/cocinas/cocina-integral.webp' },
    { id: 'cocina-cajones', name: 'Con Cajones', img: 'images/cocinas/cocina-cajones.webp' },
  ],
  vanitorys: [
    { id: 'vanitory-amplio', name: 'Amplio', img: 'images/vanitorys/vanitory-amplio.webp' },
    { id: 'vanitory-blanco', name: 'Blanco Clásico', img: 'images/vanitorys/vanitory-blanco.webp' },
    { id: 'vanitory-sencillo', name: 'Sencillo', img: 'images/vanitorys/vanitory-blanco-sencillo.webp' },
  ],
  herrajes: [
    { id: 'h-083-biselada',   name: 'Manija Biselada',        img: 'images/Herrajes/art0083_manija-biselada-de_01.webp', mesa: 'images/Herrajes/puerta_h083_biselada.png', fit: 'contain' },
    { id: 'h-083-sn',         name: 'Manija 083',             img: 'images/Herrajes/art0083_s-n_02.webp',               mesa: 'images/Herrajes/puerta_h083_sn.png',               fit: 'contain' },
    { id: 'h-098',            name: 'Manija Ministerio 098',  img: 'images/Herrajes/art0098_manijas-ministerio_01.webp', mesa: 'images/Herrajes/puerta_h098.png',             fit: 'contain' },
    { id: 'h-099',            name: 'Manija Biselada 099',    img: 'images/Herrajes/art0099_manijas-biseladas_01.webp',  mesa: 'images/Herrajes/puerta_h099.png',             fit: 'contain' },
    { id: 'h-101',            name: 'Manija 101',             img: 'images/Herrajes/art0101_manija.webp',                mesa: 'images/Herrajes/puerta_h101.png',             fit: 'contain' },
    { id: 'h-104',            name: 'Manija Giratoria',       img: 'images/Herrajes/art0104_manija-giratoria_01.webp',   mesa: 'images/Herrajes/puerta_h104.png',             fit: 'contain' },
    { id: 'h-106',            name: 'Manija Ministerio 106',  img: 'images/Herrajes/art0106_manija-ministerio.webp',     mesa: 'images/Herrajes/puerta_h106.png',             fit: 'contain' },
    { id: 'h-107',            name: 'Manija Biselada 107',    img: 'images/Herrajes/art0107_manija-biselada.webp',       mesa: 'images/Herrajes/puerta_h107.png',             fit: 'contain' },
    { id: 'h-116',            name: 'Lanín',                  img: 'images/Herrajes/art0116_lanin_02.webp',              mesa: 'images/Herrajes/puerta_h116.png',             fit: 'contain' },
    { id: 'h-142-alerce',     name: 'Manija Alerce 142',      img: 'images/Herrajes/art0142_manija-alerce_01.webp',      mesa: 'images/Herrajes/puerta_h142_alerce.png',      fit: 'contain' },
    { id: 'h-142-alerce-set', name: 'Manijas Alerce (set)',   img: 'images/Herrajes/art0142_manijas-alerce_02.webp',     mesa: 'images/Herrajes/puerta_h142_alerce_set.png',  fit: 'contain' },
    { id: 'h-143',            name: 'Manija Alerce 143',      img: 'images/Herrajes/art0143_manija-alerce_02.webp',      mesa: 'images/Herrajes/puerta_h143.png',             fit: 'contain' },
    { id: 'h-175',            name: 'Manija Trafúl 175',      img: 'images/Herrajes/art0175_manija-traful_02.webp',      mesa: 'images/Herrajes/puerta_h175.png',             fit: 'contain' },
    { id: 'h-176',            name: 'Manija Trafúl 176',      img: 'images/Herrajes/art0176_manija-traful_01.webp',      mesa: 'images/Herrajes/puerta_h176.png',             fit: 'contain' },
    { id: 'h-180',            name: 'Jacarandá Doble',        img: 'images/Herrajes/art0180_jacaranda-doble_02.webp',    mesa: 'images/Herrajes/puerta_h180.png',             fit: 'contain' },
    { id: 'h-351',            name: 'Manija Sanatorio',       img: 'images/Herrajes/art0351_manija-sanatorio_01.webp',   mesa: 'images/Herrajes/puerta_h351.png',             fit: 'contain' },
    { id: 'h-503',            name: 'Manija 503',             img: 'images/Herrajes/art0503_manija.webp',                mesa: 'images/Herrajes/puerta_h503.png',             fit: 'contain' },
    { id: 'h-506',            name: 'Manijas Biseladas',      img: 'images/Herrajes/art0506_manijas-biseladas_02.webp',  mesa: 'images/Herrajes/puerta_h506.png',             fit: 'contain' },
    { id: 'h-910',            name: 'Manijón 140cm',          img: 'images/Herrajes/art0910_manijon-de-140_02.webp',     mesa: 'images/Herrajes/puerta_h910.png',             fit: 'contain' },
    { id: 'h-911',            name: 'Manijón 220cm',          img: 'images/Herrajes/art0911_manijon-de-220_02.webp',     mesa: 'images/Herrajes/puerta_h911.png',             fit: 'contain' },
    { id: 'h-912',            name: 'Manijón 250cm',          img: 'images/Herrajes/art0912_manijon-de-250_02.webp',     mesa: 'images/Herrajes/puerta_h912.png',             fit: 'contain' },
    { id: 'h-2085',           name: 'Herraje 2085',           img: 'images/Herrajes/art2085_s-n_02.webp',               mesa: 'images/Herrajes/puerta_h2085.png',            fit: 'contain' },
  ],
  iluminacion: [
    { id: 'lum-interior',    name: 'Luminación Interior',  img: 'images/electricidad-hero.webp' },
    { id: 'lum-led',         name: 'Tecnología LED',        img: 'images/electricidad-hero.webp' },
    { id: 'instalacion',     name: 'Instalación Eléctrica', img: 'images/electricidad-hero.webp' },
    { id: 'automatizacion',  name: 'Automatización',        img: 'images/electricidad-hero.webp' },
    { id: 'lum-exterior',    name: 'Luminación Exterior',   img: 'images/electricidad-hero.webp' },
  ],
};

window.COTIZADOR_TABS = {
  stone: [
    { key: 'marmoles', label: 'Mármoles' },
    { key: 'granitos', label: 'Granitos' },
    { key: 'purastone', label: 'Purastone' },
  ],
  muebles: [
    { key: 'cocinas', label: 'Cocinas' },
    { key: 'vanitorys', label: 'Vanitorys' },
  ],
  herrajes: [
    { key: 'herrajes', label: 'Herrajes' },
  ],
  electricidad: [
    { key: 'iluminacion', label: 'Luminación' },
  ],
  all: [
    { key: 'marmoles',   label: 'Mármoles' },
    { key: 'granitos',   label: 'Granitos' },
    { key: 'purastone',  label: 'Purastone' },
    { key: 'cocinas',    label: 'Cocinas' },
    { key: 'vanitorys',  label: 'Vanitorys' },
    { key: 'herrajes',   label: 'Herrajes' },
    { key: 'iluminacion',label: 'Luminación' },
  ],
};

window.HERO_CARDS_DATA = [
  {
    id: 'marmoleria',
    title: 'Marmolería',
    subtitle: 'Mármoles, granitos y Purastone',
    img: 'images/marmoles-hero.webp',
    sectionId: 'sec-marmoleria',
    cotizadorContext: 'stone',
  },
  {
    id: 'electricidad',
    title: 'Electricidad y Luminación',
    subtitle: 'Iluminación y soluciones eléctricas',
    img: 'images/electricidad-hero.webp',
    sectionId: 'sec-electricidad',
    cotizadorContext: 'electricidad',
  },
  {
    id: 'muebles',
    title: 'Muebles de Cocina y Baño',
    subtitle: 'Diseño y fabricación a medida',
    img: 'images/cocina-completa.webp',
    sectionId: 'sec-muebles',
    cotizadorContext: 'muebles',
  },
  {
    id: 'herrajes',
    title: 'Herrajes',
    subtitle: 'Accesorios y terminaciones premium',
    img: 'images/herrajes-hero.webp',
    sectionId: 'sec-herrajes',
    cotizadorContext: 'herrajes',
  },
];

window.INFO_SECTIONS_DATA = [
  {
    id: 'sec-marmoleria',
    title: 'Marmolería',
    img: 'images/marmoles-hero.webp',
    description: 'Trabajamos con los mejores mármoles, granitos y piedras naturales del mercado. Cada pieza es cortada y pulida a medida para lograr el acabado perfecto en tu hogar u oficina.',
    features: [
      'Corte y pulido a medida',
      'Mármoles importados seleccionados',
      'Granitos nacionales e importados',
      'Purastone y Purastone Prima',
      'Instalación incluida con garantía',
    ],
    cotizadorContext: 'stone',
  },
  {
    id: 'sec-electricidad',
    title: 'Electricidad y Luminación',
    img: 'images/electricidad-hero.webp',
    description: 'Soluciones integrales en electricidad y luminación para hogares y comercios. Diseñamos y equipamos espacios con luz para realzar cada ambiente con la intensidad justa.',
    features: [
      'Instalaciones eléctricas completas',
      'Luminación de diseño interior',
      'Tecnología LED y bajo consumo',
      'Automatización del hogar',
      'Asesoramiento personalizado',
    ],
    cotizadorContext: 'electricidad',
  },
  {
    id: 'sec-muebles',
    title: 'Muebles de Cocina y Baño',
    img: 'images/cocina-completa.webp',
    description: 'Diseñamos y fabricamos muebles de cocina y baño a medida, combinando funcionalidad y estética para crear espacios únicos que se adaptan perfectamente a cada hogar.',
    features: [
      'Diseño personalizado 100%',
      'Materiales de primera calidad',
      'Cocinas integrales y en L',
      'Vanitorys y muebles de baño',
      'Entrega e instalación profesional',
    ],
    cotizadorContext: 'muebles',
  },
  {
    id: 'sec-herrajes',
    title: 'Herrajes',
    img: 'images/herrajes-hero.webp',
    description: 'Contamos con una amplia variedad de herrajes y accesorios de alta calidad para completar tus muebles y espacios con el detalle y la precisión que merecen.',
    features: [
      'Tiraderas y manijas premium',
      'Bisagras de alta resistencia',
      'Sistemas corredizos silenciosos',
      'Accesorios de cocina y baño',
      'Marcas líderes del mercado',
    ],
    cotizadorContext: 'herrajes',
  },
];
