// Data global para toda la aplicación
window.MATERIALS_DATA = {
  marmoles: [
    { id: 'botticcino',     name: 'Botticcino',     img: 'images/marmoles/Botticcino.jpeg',       mesa: 'images/mesas/botticcino.jpeg' },
    { id: 'carrara',        name: 'Carrara',         img: 'images/marmoles/Carrara.jpeg',           mesa: 'images/mesas/carrara.jpeg' },
    { id: 'negro-marquina', name: 'Negro Marquina',  img: 'images/marmoles/Negro-marquina.png',    mesa: 'images/mesas/negro-marquina.jpeg' },
    { id: 'new-beige',      name: 'New Beige',       img: 'images/marmoles/New-Beige.jpeg',         mesa: 'images/mesas/new-beige.jpeg' },
    { id: 'crema-marfil',   name: 'Crema Marfil',    img: 'images/marmoles/Crema-marfil.png',      mesa: 'images/mesas/crema-marfil.jpeg' },
    { id: 'carrara-blanco', name: 'Carrara Blanco',  img: 'images/marmoles/Carrara-Blanco.jpg',    mesa: 'images/mesas/carrara-blanco.jpeg' },
  ],
  granitos: [
    { id: 'gris-mara',        name: 'Gris Mara',        img: 'images/granitos/gris-mara.png',         mesa: 'images/mesas/gris-mara.jpeg' },
    { id: 'rosa-salto',       name: 'Rosa del Salto',   img: 'images/granitos/rosa-del-salto.jpg',    mesa: 'images/mesas/rosa-del-salto.jpeg' },
    { id: 'rosa-mara',        name: 'Rosa Mara',         img: 'images/granitos/rosa-mara.jpg',          mesa: 'images/mesas/rosa-mara.jpeg' },
    { id: 'sierra-chica',     name: 'Sierra Chica',      img: 'images/granitos/sierra-chica.jpg',       mesa: 'images/mesas/sierra-chica.jpeg' },
    { id: 'blanco-fortaleza', name: 'Blanco Fortaleza',  img: 'images/granitos/blanco-fortaleza.jpg',   mesa: 'images/mesas/blanco-fortaleza.jpeg' },
    { id: 'gris-perla',       name: 'Gris Perla',        img: 'images/granitos/gris-perla.jpeg',        mesa: 'images/mesas/gris-perla.jpeg' },
    { id: 'negro-brasil',     name: 'Negro Brasil',      img: 'images/granitos/gris-mara.png',          mesa: 'images/mesas/negro-brasil.jpeg' },
    { id: 'negro-cosmic',     name: 'Negro Cosmic',      img: 'images/granitos/gris-perla.jpeg',        mesa: 'images/mesas/negro-cosmic.jpeg' },
    { id: 'crema-julia',      name: 'Crema Julia',       img: 'images/granitos/rosa-del-salto.jpg',     mesa: 'images/mesas/crema-julia.jpeg' },
    { id: 'negro-boreal',     name: 'Negro Boreal',      img: 'images/granitos/negro-boreal.png',       mesa: 'images/mesas/negro-boreal.jpeg' },
  ],
  purastone: [
    { id: 'blanco-cana',    name: 'Blanco Caña',    img: 'images/purastone/blanco-cana.jpg',     mesa: 'images/mesas/blanco-cana.jpeg' },
    { id: 'blanco-glitter', name: 'Blanco Glitter', img: 'images/purastone/blanco-glitter.jpg',  mesa: 'images/mesas/blanco-glitter.jpeg' },
    { id: 'blanco-paloma',  name: 'Blanco Paloma',  img: 'images/purastone/blanco-paloma.jpg',   mesa: 'images/mesas/blanco-paloma.jpeg' },
    { id: 'gris-topo',      name: 'Gris Topo',      img: 'images/purastone/gris-topo.jpg',       mesa: 'images/mesas/gris-topo.jpeg' },
    { id: 'negro-glitter',  name: 'Negro Glitter',  img: 'images/purastone/negro-glitter.jpg',   mesa: 'images/mesas/negro-glitter.jpeg' },
    { id: 'blanco-nube',    name: 'Blanco Nube',    img: 'images/purastone/blanco-nube.jpg',     mesa: 'images/mesas/blanco-nube.jpeg' },
    { id: 'taj-mahal',      name: 'Taj Mahal',      img: 'images/purastone/taj-mahal.jpeg',      mesa: 'images/mesas/taj-mahal.jpeg' },
    { id: 'tundra-dark',    name: 'Tundra Dark',    img: 'images/purastone/tundra-dark.jpeg',    mesa: 'images/mesas/tundra-dark.jpeg' },
    { id: 'gris-fosil',     name: 'Gris Fósil',     img: 'images/purastone/blanco-paloma.jpg',   mesa: 'images/mesas/gris-fosil.jpeg' },
    { id: 'gris-zen',       name: 'Gris Zen',       img: 'images/purastone/gris-topo.jpg',       mesa: 'images/mesas/gris-zen.jpeg' },
  ],
  cocinas: [
    { id: 'cocina-l', name: 'Cocina en L', img: 'images/cocinas/cocina-L.png' },
    { id: 'cocina-integral', name: 'Cocina Integral', img: 'images/cocinas/cocina-integral.png' },
    { id: 'cocina-cajones', name: 'Con Cajones', img: 'images/cocinas/cocina-cajones.png' },
  ],
  vanitorys: [
    { id: 'vanitory-amplio', name: 'Amplio', img: 'images/vanitorys/vanitory-amplio.png' },
    { id: 'vanitory-blanco', name: 'Blanco Clásico', img: 'images/vanitorys/vanitory-blanco.png' },
    { id: 'vanitory-sencillo', name: 'Sencillo', img: 'images/vanitorys/vanitory-blanco-sencillo.png' },
  ],
  herrajes: [
    { id: 'h-083-biselada',   name: 'Manija Biselada',        img: 'images/Herrajes/art0083_manija-biselada-de_01.png', mesa: 'images/Herrajes/art0083_manija-biselada-de_02.png', fit: 'contain' },
    { id: 'h-083-sn',         name: 'Manija 083',             img: 'images/Herrajes/art0083_s-n_02.png',               mesa: 'images/Herrajes/art0083_s-n_01.png',               fit: 'contain' },
    { id: 'h-098',            name: 'Manija Ministerio 098',  img: 'images/Herrajes/art0098_manijas-ministerio_01.png', mesa: 'images/Herrajes/art0098_manijas-ministerio_02.png', fit: 'contain' },
    { id: 'h-099',            name: 'Manija Biselada 099',    img: 'images/Herrajes/art0099_manijas-biseladas_01.png',  mesa: 'images/Herrajes/art0099_manijas-biseladas_02.png',  fit: 'contain' },
    { id: 'h-101',            name: 'Manija 101',             img: 'images/Herrajes/art0101_manija.png',                mesa: 'images/Herrajes/art0101_manija.png',                fit: 'contain' },
    { id: 'h-104',            name: 'Manija Giratoria',       img: 'images/Herrajes/art0104_manija-giratoria_01.png',   mesa: 'images/Herrajes/art0104_manija-giratoria_02.png',   fit: 'contain' },
    { id: 'h-106',            name: 'Manija Ministerio 106',  img: 'images/Herrajes/art0106_manija-ministerio.png',     mesa: 'images/Herrajes/art0106_manija-ministerio.png',     fit: 'contain' },
    { id: 'h-107',            name: 'Manija Biselada 107',    img: 'images/Herrajes/art0107_manija-biselada.png',       mesa: 'images/Herrajes/art0107_manija-biselada.png',       fit: 'contain' },
    { id: 'h-116',            name: 'Lanín',                  img: 'images/Herrajes/art0116_lanin_02.png',              mesa: 'images/Herrajes/art0116_lanin_01.png',              fit: 'contain' },
    { id: 'h-142-alerce',     name: 'Manija Alerce 142',      img: 'images/Herrajes/art0142_manija-alerce_01.png',      mesa: 'images/Herrajes/art0142_manija-alerce_02.png',      fit: 'contain' },
    { id: 'h-142-alerce-set', name: 'Manijas Alerce (set)',   img: 'images/Herrajes/art0142_manijas-alerce_02.png',     mesa: 'images/Herrajes/art0142_manijas-alerce_01.png',     fit: 'contain' },
    { id: 'h-143',            name: 'Manija Alerce 143',      img: 'images/Herrajes/art0143_manija-alerce_02.png',      mesa: 'images/Herrajes/art0143_manija-alerce_01.png',      fit: 'contain' },
    { id: 'h-175',            name: 'Manija Trafúl 175',      img: 'images/Herrajes/art0175_manija-traful_02.png',      mesa: 'images/Herrajes/art0175_manija-traful_01.png',      fit: 'contain' },
    { id: 'h-176',            name: 'Manija Trafúl 176',      img: 'images/Herrajes/art0176_manija-traful_01.png',      mesa: 'images/Herrajes/art0176_manija-traful_02.png',      fit: 'contain' },
    { id: 'h-180',            name: 'Jacarandá Doble',        img: 'images/Herrajes/art0180_jacaranda-doble_02.png',    mesa: 'images/Herrajes/art0180_jacaranda-doble_01.png',    fit: 'contain' },
    { id: 'h-351',            name: 'Manija Sanatorio',       img: 'images/Herrajes/art0351_manija-sanatorio_01.png',   mesa: 'images/Herrajes/art0351_manija-sanatorio_02.png',   fit: 'contain' },
    { id: 'h-503',            name: 'Manija 503',             img: 'images/Herrajes/art0503_manija.png',                mesa: 'images/Herrajes/art0503_manija.png',                fit: 'contain' },
    { id: 'h-506',            name: 'Manijas Biseladas',      img: 'images/Herrajes/art0506_manijas-biseladas_02.png',  mesa: 'images/Herrajes/art0506_manijas-biseladas_01.png',  fit: 'contain' },
    { id: 'h-910',            name: 'Manijón 140cm',          img: 'images/Herrajes/art0910_manijon-de-140_02.png',     mesa: 'images/Herrajes/art0910_manijon-de-140_01.png',     fit: 'contain' },
    { id: 'h-911',            name: 'Manijón 220cm',          img: 'images/Herrajes/art0911_manijon-de-220_02.png',     mesa: 'images/Herrajes/art0911_manijon-de-220_01.png',     fit: 'contain' },
    { id: 'h-912',            name: 'Manijón 250cm',          img: 'images/Herrajes/art0912_manijon-de-250_02.png',     mesa: 'images/Herrajes/art0912_manijon-de-250_01.png',     fit: 'contain' },
    { id: 'h-2085',           name: 'Herraje 2085',           img: 'images/Herrajes/art2085_s-n_02.png',               mesa: 'images/Herrajes/art2085_s-n_01.png',               fit: 'contain' },
  ],
  iluminacion: [
    { id: 'lum-interior',    name: 'Luminación Interior',  img: 'images/electricidad-hero.png' },
    { id: 'lum-led',         name: 'Tecnología LED',        img: 'images/electricidad-hero.png' },
    { id: 'instalacion',     name: 'Instalación Eléctrica', img: 'images/electricidad-hero.png' },
    { id: 'automatizacion',  name: 'Automatización',        img: 'images/electricidad-hero.png' },
    { id: 'lum-exterior',    name: 'Luminación Exterior',   img: 'images/electricidad-hero.png' },
  ],
};

window.COTIZADOR_TABS = {
  stone: [
    { key: 'marmoles', label: 'Mármoles' },
    { key: 'granitos', label: 'Granitos' },
    { key: 'purastone', label: 'Purastone' },
  ],
  muebles: [
    { key: 'cocinas', label: 'Cocinas' },
    { key: 'vanitorys', label: 'Vanitorys' },
  ],
  herrajes: [
    { key: 'herrajes', label: 'Herrajes' },
  ],
  electricidad: [
    { key: 'iluminacion', label: 'Luminación' },
  ],
  all: [
    { key: 'marmoles',   label: 'Mármoles' },
    { key: 'granitos',   label: 'Granitos' },
    { key: 'purastone',  label: 'Purastone' },
    { key: 'cocinas',    label: 'Cocinas' },
    { key: 'vanitorys',  label: 'Vanitorys' },
    { key: 'herrajes',   label: 'Herrajes' },
    { key: 'iluminacion',label: 'Luminación' },
  ],
};

window.HERO_CARDS_DATA = [
  {
    id: 'marmoleria',
    title: 'Marmolería',
    subtitle: 'Mármoles, granitos y Purastone',
    img: 'images/marmoles-hero.png',
    sectionId: 'sec-marmoleria',
    cotizadorContext: 'stone',
  },
  {
    id: 'electricidad',
    title: 'Electricidad y Luminación',
    subtitle: 'Iluminación y soluciones eléctricas',
    img: 'images/electricidad-hero.png',
    sectionId: 'sec-electricidad',
    cotizadorContext: 'electricidad',
  },
  {
    id: 'muebles',
    title: 'Muebles de Cocina y Baño',
    subtitle: 'Diseño y fabricación a medida',
    img: 'images/cocina-completa.jpg',
    sectionId: 'sec-muebles',
    cotizadorContext: 'muebles',
  },
  {
    id: 'herrajes',
    title: 'Herrajes',
    subtitle: 'Accesorios y terminaciones premium',
    img: 'images/herrajes-hero.png',
    sectionId: 'sec-herrajes',
    cotizadorContext: 'herrajes',
  },
];

window.INFO_SECTIONS_DATA = [
  {
    id: 'sec-marmoleria',
    title: 'Marmolería',
    img: 'images/marmoles-hero.png',
    description: 'Trabajamos con los mejores mármoles, granitos y piedras naturales del mercado. Cada pieza es cortada y pulida a medida para lograr el acabado perfecto en tu hogar u oficina.',
    features: [
      'Corte y pulido a medida',
      'Mármoles importados seleccionados',
      'Granitos nacionales e importados',
      'Purastone y Purastone Prima',
      'Instalación incluida con garantía',
    ],
    cotizadorContext: 'stone',
  },
  {
    id: 'sec-electricidad',
    title: 'Electricidad y Luminación',
    img: 'images/electricidad-hero.png',
    description: 'Soluciones integrales en electricidad y luminación para hogares y comercios. Diseñamos y equipamos espacios con luz para realzar cada ambiente con la intensidad justa.',
    features: [
      'Instalaciones eléctricas completas',
      'Luminación de diseño interior',
      'Tecnología LED y bajo consumo',
      'Automatización del hogar',
      'Asesoramiento personalizado',
    ],
    cotizadorContext: 'electricidad',
  },
  {
    id: 'sec-muebles',
    title: 'Muebles de Cocina y Baño',
    img: 'images/cocina-completa.jpg',
    description: 'Diseñamos y fabricamos muebles de cocina y baño a medida, combinando funcionalidad y estética para crear espacios únicos que se adaptan perfectamente a cada hogar.',
    features: [
      'Diseño personalizado 100%',
      'Materiales de primera calidad',
      'Cocinas integrales y en L',
      'Vanitorys y muebles de baño',
      'Entrega e instalación profesional',
    ],
    cotizadorContext: 'muebles',
  },
  {
    id: 'sec-herrajes',
    title: 'Herrajes',
    img: 'images/herrajes-hero.png',
    description: 'Contamos con una amplia variedad de herrajes y accesorios de alta calidad para completar tus muebles y espacios con el detalle y la precisión que merecen.',
    features: [
      'Tiraderas y manijas premium',
      'Bisagras de alta resistencia',
      'Sistemas corredizos silenciosos',
      'Accesorios de cocina y baño',
      'Marcas líderes del mercado',
    ],
    cotizadorContext: 'herrajes',
  },
];
